sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

language: go
go_import_path: github.com/v3io/scaler
go: "1.11"

script:
  - make lint test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "development" ]; then
    export SCALER_LABEL="unstable";
    fi
  - if [ "$TRAVIS_TAG" != "" ]; then
    export SCALER_LABEL="$TRAVIS_TAG";
    fi
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - if [ -n "$SCALER_LABEL" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin &&
    make docker-images push-docker-images;
    fi
  - echo "Done."
